# Generated by Django 3.2.8 on 2022-02-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefix',
            field=models.CharField(default='Mr', max_length=5),
            preserve_default=False,
        ),
    ]
