# Generated by Django 3.2.8 on 2022-02-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseactivities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseactivity',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='exerciseactivity',
            old_name='user_id',
            new_name='user',
        ),
    ]
