# Generated by Django 3.2.8 on 2022-02-18 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exerciseactivities', '0002_auto_20220210_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseactivity',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseactivity',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
